### ISSUE TITLE
Store error messages as part of the deployment

### ISSUE THREAD

**Issue by bmelville** [kubernetes/deployment-manager#79]
When a deployment fails, we should store error messages along-side the status inside the deployment

**Comment by zmerlynn** [comment]
Do you want to store the deployment at all if the expansion fails? I was just surprised by:

```
$ dm deploy templates/spark/v1/spark.yaml
2015/11/19 16:45:55 cannot deploy configuration named spark.yaml: status code: 400 status: 400 Bad Request : cannot expand template named spark.yaml (template expansion: expandybird response:
error expanding template: error expanding template spark.yaml: Traceback (most recent call last):
  File "./expansion/expansion.py", line 372, in <module>
    main()
  File "./expansion/expansion.py", line 369, in main
    print Expand(template, imports, env=env, validate_schema=validate_schema)
  File "./expansion/expansion.py", line 57, in Expand
    raise ExpansionError('config', str(e))
__main__.ExpansionError: unexpected '}' Resource: config
):
imports:
- path: spark.jinja

resources:
- name: spark
  type: spark.jinja


zml@zml:~/deployment-manager$ dm deploy templates/spark/v1/spark.yaml 
2015/11/19 16:49:12 cannot deploy configuration named spark.yaml: status code: 400 status: 400 Bad Request : Deployment spark.yaml already exists
```

**Comment by vaikas-google** [comment]
Yeah, so the thinking was that the flow would be deploy, if it fails, you'd look at the errors and update. However, if it seems like it's more natural to fail fast and not even create a deployment, I can change the semantics. Unless somebody complains loudly about this, I can make the change.

**Comment by bmelville** [comment]
That change will be hard to keep around once we move to an asynchronous API.
